version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: property_mgmt_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d property_mgmt_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    image: node:20-alpine
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://postgres:password@postgres:5432/property_mgmt_dev
      SESSION_SECRET: devsecret
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm ci && node src/server.js"
    ports:
      - "3002:3000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres_test:
    image: postgres:15
    environment:
      POSTGRES_DB: property_mgmt_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d property_mgmt_test"]
      interval: 5s
      timeout: 5s
      retries: 10
    
  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: 
  postgres_test_data: