name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: property_mgmt_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d property_mgmt_test"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            Property Mgmt Test/package-lock.json

      - name: Install dependencies
        working-directory: 'Property Mgmt Test'
        run: npm ci

      - name: Lint
        working-directory: 'Property Mgmt Test'
        run: npm run lint

      - name: Run tests
        working-directory: 'Property Mgmt Test'
        env:
          NODE_ENV: test
          TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/property_mgmt_test
          CLIENT_BASE_URL: http://localhost:5173
          JWT_SECRET: ci_test_secret
        run: npm test


